### ISSUE TITLE
Time & date standardization

### ISSUE THREAD

**Issue by cody-henderson** [hhandika/nahpu#25]
@hhandika @AndreMonc while working on #24, I noticed that we're storing time and date data as simple text in the database, in whatever local format the user is working in. This doesn't cause a problem when using the app on a single machine in a consistent time zone, but I think things get weird if the database is shared to another user with different settings.

For instance, my Mac is set to 24 hour time and my Windows PC is set to 12 hour time. If I set a "Collection time" of 4 PM on my Windows machine, the DB stores "4:00 PM". After copying the DB to my Mac, the "4:00 PM" value still displays, but editing the field then changes the value to 24 hour time. If I select 4 PM again, the DB now stores "16:00", and we potentially have a mix of 12 and 24 hour time data. I imagine this gets potentially more problematic if the machines were in different time zones. 

Would we be interested in updating the date/time fields to be stored as [timestamps or ISO8601 strings](https://drift.simonbinder.eu/guides/datetime-migrations/)? This could eliminate the issues above. It would also facilitate retaining date/time field data when pickers are opened as we discussed as a future enhancement in #24, which right now isn't feasible due to the potential for different date/time formats across users.

**Comment by hhandika** [comment]
I agree with the migration. It will be a good addition to our effort to support the FAIR principles. This was overlooked when I implemented the date and time fields. I wonder ISO8601 will be a better option.

**Comment by Larry-Gan** [comment]
ISO8601 should work fine right? Since it's standardized while still being readable. We probably need to specify somehow that the times are always UTC tho. 
Also would we need to support users exporting to their own timezone?

**Comment by cody-henderson** [comment]
I think we would keep the current behavior where the dates/times are displayed to the user in their local timezone/format, even though we're storing them in UTC.

**Comment by Larry-Gan** [comment]
Yeah that makes sense, although wouldn't it be an issue if we're exporting and another person in a different timezone reads the export and they don't know what timezone they should use if we let users choose? Guess it's not an issue if we somehow note down the timezone in the export, or default to UTC on exports.
Not sure how major that issue would be tho.

**Comment by AndreMonc** [comment]
@cody-henderson @Larry-Gan @hhandika I'm not sure I follow 100% the discussion about time zones. We don't need to accommodate dates/times to users opening up NAHPU in a different time zone (though the time format still appears to be an issue). All dates/times should be displayed in the time zone of the original specimen collection. Is there a way to lock that original time/date to a zone after entry? For example, if I use specimen data from say, Indonesia, I would definitely assume any times were in the local time zone based on the specimen locality information. Museum data is very specimen-focused rather than user-focused. Make sense?

**Comment by cody-henderson** [comment]
@AndreMonc this is really useful context! Thank you. It does make sense. Would it likely be the case that at a project level, all the specimen data would be collected/entered with a consistent time zone? I could imagine that being a project-level setting for either/both data entry and data display.

**Comment by AndreMonc** [comment]
@cody-henderson Yes, at a project level the time zone would be consistent. I believe you're onto something with the project-level setting for the time zone and format parameters.

**Comment by hhandika** [comment]
Hi @AndreMonc, @cody-henderson, it won't always be the same time zone. For example, for fieldwork on Sulawesi, I will start writing my narrative when I leave Baton Rouge. Within Indonesia, the data entry beyond narrative can be in two different time zones. 

Our best option is to record the time zone following ISO 8601. This will also match the Darwin Core recommendation. Here is the example from [DWC eventDate](https://dwc.tdwg.org/terms/#event):
`1963-03-08T14:07-06:00 (8 Mar 1963 at or after 2:07 pm and before 2:08 pm in the time zone six hours earlier than UTC)` 

I agree we should have data/time formats in the settings. We can include a tick box to use the same format for data export.

**Comment by AndreMonc** [comment]
Hey @hhandika good point about the narrative being written later in a different time zone--in that case using the local time and time zone makes sense. My main concern was about specimen collection dates/times getting modified if someone from a different time zone uploads the database--the displayed and exported dates/times should be those associated with the locality where the specimen was collected.

Or, take another example, what about somebody entering data into NAHPU from a past expedition that was conducted in a different time zone? In order to add the appropriate and biologically relevant collection time, they would need a way to manually assign the time zone and not take the default based on their current location.

Anyways, excited that the time feature developments are moving forward! Will be great to chat more about this.

**Comment by hhandika** [comment]
Hi @AndreMonc, for viewing the existing database, it should have no effect. Nothing will be ingested into the database. We need to make sure we handle it properly for viewing dates/times that have no timezone for backward compatibility. 

For viewing, we can either hide the time zone from users entirely or add a note under the fields indicating UTC-XX when it is available. 

For editing the data, we need to find a way to allow users to adjust the time zone. Having this option in the project settings will be useful. We could also add an option not to record the time zone because most museums won't care much it.

Agreed to chat more about this. Date/time is critical information.

**Comment by felideon** [comment]
I'm not too sure about #48. Depending on how it's implemented, a "project time zone" may be a bit too heavy-handed, as illustrated by @hhandika's example of working on the same project across time zones.

As far as writing/editing the data, agreed with @AndreMonc that having control over the offset/timezone would be important. When creating a new record, it could default to the device timezone, assuming devices connect to the internet at least once to synchronize to local time. Otherwise, a project default time zone setting makes sense. When editing an existing record, the default should be to maintain the timezone of the existing record. In either case, there should be an affordance for a manual override (e.g. for corrections).

Also, I was reading[[1]](https://event-driven.io/en/is_keeping_utc_dates_best_solution/)[[2]](https://codeblog.jonskeet.uk/2019/03/27/storing-utc-is-not-a-silver-bullet/) about time zones and, if I understand correctly, specimen collection times would ideally be encoded with both offset _and_ timezone (which means ISO 8601 alone won't suffice) _at the moment of collection_ to avoid ambiguity.

I don't know how realistic of a scenario this is, but let's say I'm in Leticia, Colombia in the morning and I cross over to Tabatinga, Brazil in the afternoon. Same offset (UTC-5), but different time zones. It may not make much of a difference in practice, but it could be an important piece of historical information and would eliminate the guesswork when viewing/consuming the data: if all they can see is the offset, the time zone might as well be EST for all they know. There's no way to know _why_ that's the given offset, unless it's inferred from the geocoordinates or project data.

Implementation-wise, since ISO 8601 only encodes offset and not time zone, we'd need a separate field to store the time zone. So whether it is actually worth it is up for debate.

**Comment by hhandika** [comment]
Those are great points, @felideon . We may be fine to only record the offset to make sure the data is displayed as it was entered in the field. Most museums, when they export data, will only care about the date and time. The offset will only matter when we implement DWC format export: `1963-03-08T14:07-06:00`.
